/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedHandoffRouteImport } from './routes/_authenticated.handoff'
import { Route as AuthenticatedInventoryManagementRouteImport } from './routes/_authenticated.inventory-management'
import { Route as AuthenticatedKitchenRouteImport } from './routes/_authenticated.kitchen'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated.sales'
import { Route as AuthenticatedStaffManagementRouteImport } from './routes/_authenticated.staff-management'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHandoffRoute = AuthenticatedHandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryManagementRoute =
  AuthenticatedInventoryManagementRouteImport.update({
    id: '/inventory-management',
    path: '/inventory-management',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKitchenRoute = AuthenticatedKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStaffManagementRoute =
  AuthenticatedStaffManagementRouteImport.update({
    id: '/staff-management',
    path: '/staff-management',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/handoff': typeof AuthenticatedHandoffRoute
  '/inventory-management': typeof AuthenticatedInventoryManagementRoute
  '/kitchen': typeof AuthenticatedKitchenRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/staff-management': typeof AuthenticatedStaffManagementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/handoff': typeof AuthenticatedHandoffRoute
  '/inventory-management': typeof AuthenticatedInventoryManagementRoute
  '/kitchen': typeof AuthenticatedKitchenRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/staff-management': typeof AuthenticatedStaffManagementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/handoff': typeof AuthenticatedHandoffRoute
  '/_authenticated/inventory-management': typeof AuthenticatedInventoryManagementRoute
  '/_authenticated/kitchen': typeof AuthenticatedKitchenRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/staff-management': typeof AuthenticatedStaffManagementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/handoff'
    | '/inventory-management'
    | '/kitchen'
    | '/sales'
    | '/staff-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/handoff'
    | '/inventory-management'
    | '/kitchen'
    | '/sales'
    | '/staff-management'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/handoff'
    | '/_authenticated/inventory-management'
    | '/_authenticated/kitchen'
    | '/_authenticated/sales'
    | '/_authenticated/staff-management'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/handoff': {
      id: '/_authenticated/handoff'
      path: '/handoff'
      fullPath: '/handoff'
      preLoaderRoute: typeof AuthenticatedHandoffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory-management': {
      id: '/_authenticated/inventory-management'
      path: '/inventory-management'
      fullPath: '/inventory-management'
      preLoaderRoute: typeof AuthenticatedInventoryManagementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kitchen': {
      id: '/_authenticated/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof AuthenticatedKitchenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff-management': {
      id: '/_authenticated/staff-management'
      path: '/staff-management'
      fullPath: '/staff-management'
      preLoaderRoute: typeof AuthenticatedStaffManagementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedHandoffRoute: typeof AuthenticatedHandoffRoute
  AuthenticatedInventoryManagementRoute: typeof AuthenticatedInventoryManagementRoute
  AuthenticatedKitchenRoute: typeof AuthenticatedKitchenRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedStaffManagementRoute: typeof AuthenticatedStaffManagementRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHandoffRoute: AuthenticatedHandoffRoute,
  AuthenticatedInventoryManagementRoute: AuthenticatedInventoryManagementRoute,
  AuthenticatedKitchenRoute: AuthenticatedKitchenRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedStaffManagementRoute: AuthenticatedStaffManagementRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
