/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as StaffRouteImport } from './routes/_staff'
import { Route as AdminInventoryManagementRouteImport } from './routes/_admin.inventory-management'
import { Route as AdminStaffManagementRouteImport } from './routes/_admin.staff-management'
import { Route as StaffHandoffRouteImport } from './routes/_staff.handoff'
import { Route as StaffKitchenRouteImport } from './routes/_staff.kitchen'
import { Route as StaffOrderManagementRouteImport } from './routes/_staff.order-management'
import { Route as StaffSalesRouteImport } from './routes/_staff.sales'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/_staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryManagementRoute =
  AdminInventoryManagementRouteImport.update({
    id: '/inventory-management',
    path: '/inventory-management',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminStaffManagementRoute = AdminStaffManagementRouteImport.update({
  id: '/staff-management',
  path: '/staff-management',
  getParentRoute: () => AdminRoute,
} as any)
const StaffHandoffRoute = StaffHandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => StaffRoute,
} as any)
const StaffKitchenRoute = StaffKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => StaffRoute,
} as any)
const StaffOrderManagementRoute = StaffOrderManagementRouteImport.update({
  id: '/order-management',
  path: '/order-management',
  getParentRoute: () => StaffRoute,
} as any)
const StaffSalesRoute = StaffSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => StaffRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inventory-management': typeof AdminInventoryManagementRoute
  '/staff-management': typeof AdminStaffManagementRoute
  '/handoff': typeof StaffHandoffRoute
  '/kitchen': typeof StaffKitchenRoute
  '/order-management': typeof StaffOrderManagementRoute
  '/sales': typeof StaffSalesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inventory-management': typeof AdminInventoryManagementRoute
  '/staff-management': typeof AdminStaffManagementRoute
  '/handoff': typeof StaffHandoffRoute
  '/kitchen': typeof StaffKitchenRoute
  '/order-management': typeof StaffOrderManagementRoute
  '/sales': typeof StaffSalesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_staff': typeof StaffRouteWithChildren
  '/_admin/inventory-management': typeof AdminInventoryManagementRoute
  '/_admin/staff-management': typeof AdminStaffManagementRoute
  '/_staff/handoff': typeof StaffHandoffRoute
  '/_staff/kitchen': typeof StaffKitchenRoute
  '/_staff/order-management': typeof StaffOrderManagementRoute
  '/_staff/sales': typeof StaffSalesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inventory-management'
    | '/staff-management'
    | '/handoff'
    | '/kitchen'
    | '/order-management'
    | '/sales'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inventory-management'
    | '/staff-management'
    | '/handoff'
    | '/kitchen'
    | '/order-management'
    | '/sales'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_staff'
    | '/_admin/inventory-management'
    | '/_admin/staff-management'
    | '/_staff/handoff'
    | '/_staff/kitchen'
    | '/_staff/order-management'
    | '/_staff/sales'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff': {
      id: '/_staff'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/inventory-management': {
      id: '/_admin/inventory-management'
      path: '/inventory-management'
      fullPath: '/inventory-management'
      preLoaderRoute: typeof AdminInventoryManagementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/staff-management': {
      id: '/_admin/staff-management'
      path: '/staff-management'
      fullPath: '/staff-management'
      preLoaderRoute: typeof AdminStaffManagementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_staff/handoff': {
      id: '/_staff/handoff'
      path: '/handoff'
      fullPath: '/handoff'
      preLoaderRoute: typeof StaffHandoffRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/kitchen': {
      id: '/_staff/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof StaffKitchenRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/order-management': {
      id: '/_staff/order-management'
      path: '/order-management'
      fullPath: '/order-management'
      preLoaderRoute: typeof StaffOrderManagementRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/sales': {
      id: '/_staff/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof StaffSalesRouteImport
      parentRoute: typeof StaffRoute
    }
  }
}

interface AdminRouteChildren {
  AdminInventoryManagementRoute: typeof AdminInventoryManagementRoute
  AdminStaffManagementRoute: typeof AdminStaffManagementRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInventoryManagementRoute: AdminInventoryManagementRoute,
  AdminStaffManagementRoute: AdminStaffManagementRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StaffRouteChildren {
  StaffHandoffRoute: typeof StaffHandoffRoute
  StaffKitchenRoute: typeof StaffKitchenRoute
  StaffOrderManagementRoute: typeof StaffOrderManagementRoute
  StaffSalesRoute: typeof StaffSalesRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffHandoffRoute: StaffHandoffRoute,
  StaffKitchenRoute: StaffKitchenRoute,
  StaffOrderManagementRoute: StaffOrderManagementRoute,
  StaffSalesRoute: StaffSalesRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
